@startuml

usecase (gérer compte) as UC_Gerer_Compte
usecase (gérer son compte) as UC_Gerer_Compte2
usecase (gérer catalogue) as UC_Gerer_Catalogue
usecase (gérer entreprise cliente) as UC_Gerer_Entreprise
usecase (gérer commande) as UC_Gerer_Commande
usecase (modifier le mot de passe) as UC_MDP
usecase (modifier le mot de passe) as UC_MDP2
usecase (gérer les produits) as UC_G_Produit
usecase (gérer les catégories) as UC_G_Categorie
usecase (gérer les utilisateurs) as UC_G_Utils
usecase (gérer les salariés) as UC_Gerer_Salaries
usecase (visualiser le catalogue) as UC_Voir_Catalogue
usecase (gérer le panier) as UC_G_Panier
usecase (visualiser les commandes) as UC_Voir_Commande
usecase (ajouter un produit dans le panier) as UC_Ajout_Panier

actor :administrateur du logiciel: as admin
actor :rédacteur Cafe: as redacCafe
actor :commercialCafe: as comCafe
actor :entreprise cliente: as entreprise
actor :salarié entreprise cliente: as salarie


admin --> UC_Gerer_Compte
admin --> UC_G_Utils

redacCafe --> UC_Gerer_Catalogue

comCafe --> UC_Gerer_Entreprise
comCafe --> UC_Gerer_Commande

entreprise --> UC_Gerer_Entreprise
entreprise --> UC_Gerer_Salaries
entreprise --> UC_Gerer_Compte2

salarie --> UC_Voir_Catalogue
salarie --> UC_G_Panier
salarie --> UC_Voir_Commande
salarie --> UC_Gerer_Compte2

UC_Gerer_Compte --> UC_MDP
UC_Gerer_Compte2 --> UC_MDP2
UC_Gerer_Catalogue --> UC_G_Produit
UC_Gerer_Catalogue --> UC_G_Categorie
UC_Voir_Catalogue --> UC_Ajout_Panier

@enduml
